### ISSUE TITLE
In train.py, There is no 'P2' argument in Propagate_MS made by xanderchf

### ISSUE THREAD

**Issue by tolry418** [seoungwugoh/RGMP#11]
Hello. 
I tried the RGMP code to understand it. 
And i use the code made by xanderchf. 
but there is missing argument in the middle of code. 
How can i solve it.  

Error was occurred in here 
for f in range(0, num_bptt - 1):
    output, ms = Propagate_MS(ms, all_F[:,:,f+1], all_E[:,0,f])

TypeError: Propagate_MS() missing 1 required positional argument: 'P2'

Thanks you in advance.

**Comment by simantika** [comment]
How did u solve this error??

**Comment by simantika** [comment]
> Hello.
> I tried the RGMP code to understand it.
> And i use the code made by xanderchf.
> but there is missing argument in the middle of code.
> How can i solve it.
> 
> Error was occurred in here
> for f in range(0, num_bptt - 1):
> output, ms = Propagate_MS(ms, all_F[:,:,f+1], all_E[:,0,f])
> 
> TypeError: Propagate_MS() missing 1 required positional argument: 'P2'
> 
> Thanks you in advance.

Please help me in solving this error.
