### ISSUE TITLE
Train with youtube-vos

### ISSUE THREAD

**Issue by siyueyu** [seoungwugoh/RGMP#13]
Sorry to bother you.Have you tried the youtube-vos dataset. Can it work?  I have tried the youtube-vos dataset. But I failed to make it work.

**Comment by seoungwugoh** [comment]
Hi siyueyu, 
I haven't tried it, but I don't think there's a reason to fail if your training script works well for DAVIS. 
Learning from larger training data is expected to make learning more stable. 
The model may no longer need pre-training.

Hope you get good results!

**Comment by siyueyu** [comment]
@seoungwugoh 
Thanks for your reply, I will try again.
