### ISSUE TITLE
Implement three measures

### ISSUE THREAD

**Issue by InstantWindy** [seoungwugoh/RGMP#4]
Hello! I am a newcomer to learning video segmentation. Do you implement three measures:region similarity,contour accuracy and temporal instability? Thank you !

**Comment by seoungwugoh** [comment]
Use the evaluation tool from the DAVIS challenges:
https://davischallenge.org/davis2017/code.html

**Comment by InstantWindy** [comment]
I have a question about the official code "jaccard.py" file and the "f_boundary.py" file.But I don't know what the input parameters of the db_eval_iou function of the'jaccard.py'file and  'db_eval_boundary' function of the 'f_boundary.py' file should be? Thank you!

**Comment by seoungwugoh** [comment]
You should ask the question on DAVIS repository.
